filter:
    excluded_paths:
        - tests/*
        - lib/*

checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        php:
            version: 5.5.9

    tests:
        override:
            -
                command: 'phpunit --coverage-clover=some-file'
                coverage:
                    file: 'some-file'
                    format: 'php-clover'
